### PR TITLE
Commit board map file and driver updates for PicoBOB board.

### PR DESCRIPTION
**Pull request by andrewmarles**
Some fixes in the driver to support axes ganging when using GPIO.

The PicoBOB is a low cost and simple GRBLHAL board to work with the common Mach3 BOB.

image

### CODE REVIEW

**Comment by andrewmarles** [comment]
Will be posting the hardware files to my github once I have written the readme.  Same thing we did with GRBLHAL2000.

**Comment by andrewmarles** [comment]
PicoBOB files are posted

https://github.com/Expatria-Technologies/PicoBOB

**Comment by terjeio** [comment]
FYI I have refactored and cleaned up the code as it was becoming a bit messy, can you retest your board with the latest commit?

**Comment by andrewmarles** [comment]
Will test and report any issues.  Have a few users running machines on picobob and they seem happy.

**Pull request merged**
